// <auto-generated />
using ExamenDAW.ContextModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamenDAW.Migrations
{
    [DbContext(typeof(ExamContext))]
    [Migration("20240125123019_SecondCreate")]
    partial class SecondCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExamenDAW.Entities.Materie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Materii");
                });

            modelBuilder.Entity("ExamenDAW.Entities.Profesor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Profesori");
                });

            modelBuilder.Entity("ExamenDAW.Entities.ProfesorMaterie", b =>
                {
                    b.Property<int>("IdProfesor")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("IdMaterie")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("MaterieId")
                        .HasColumnType("int");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("int");

                    b.HasKey("IdProfesor", "IdMaterie");

                    b.HasIndex("MaterieId");

                    b.HasIndex("ProfesorId");

                    b.ToTable("ProfesoriMaterii");
                });

            modelBuilder.Entity("ExamenDAW.Entities.ProfesorMaterie", b =>
                {
                    b.HasOne("ExamenDAW.Entities.Materie", "Materie")
                        .WithMany("ProfesoriMaterii")
                        .HasForeignKey("MaterieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamenDAW.Entities.Profesor", "Profesor")
                        .WithMany("ProfesoriMaterii")
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materie");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("ExamenDAW.Entities.Materie", b =>
                {
                    b.Navigation("ProfesoriMaterii");
                });

            modelBuilder.Entity("ExamenDAW.Entities.Profesor", b =>
                {
                    b.Navigation("ProfesoriMaterii");
                });
#pragma warning restore 612, 618
        }
    }
}
